### ISSUE TITLE
"Creating service broker" is failing with error code 270013

### ISSUE THREAD

**Issue by deltatree** [cloudfoundry-community/docker-broker-deployment#4]
Creating service broker docker-broker as admin...
           FAILED
           Server error, status code: 502, error code: 270013, message: Service broker dashboard clients could not be modified: The UAA request was invalid

**Comment by deltatree** [comment]
Bosh lite on virtualbox with "https://github.com/cloudfoundry/bosh-deployment/blob/master/docs/bosh-lite-on-vbox.md"
Server behind proxy with MITM - Proxy is set and also the company ca is via yml properties injected

**Comment by deltatree** [comment]
docker pull is fully functional, but if I look in the fetch containers logfiles:
cat /var/vcap/data/sys/log/cf-containers-broker/fetch_containers_images*
I find following error:
ERROR -- : +-> Cannot fetch Docker image `frodenas/rabbitmq:latest': #<Docker::Error::TimeoutError: read timeout reached

Manually I can fetch the images:
~# docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
frodenas/redis        3.2                 519eacfe3c4d        2 months ago        420 MB
frodenas/postgresql   9.6                 ba7a02cb2034        2 months ago        476 MB
frodenas/mysql        5.6                 e63194440730        3 months ago        688 MB
frodenas/mongodb      2.6                 01550e572644        3 months ago        697 MB
frodenas/rabbitmq     latest              7ed3b14d19f9        19 months ago       427 MB
frodenas/couchdb      1.6                 c8f68b6eb30a        20 months ago       537 MB

**Comment by deltatree** [comment]
@drnic some ideas?

**Comment by ramonskie** [comment]
do not provide http or https in
`-v broker_route_uri=<docker-broker.mycf.com>`

**Comment by aeijdenberg** [comment]
FYI we had a similar issue (or at least error code). I managed to track it down to CF expecting a completed `dashboard_client` be present in the `/v2/catalog` response. In our case, we didn't need that, so I "fixed" by this [pull request](https://github.com/cloudfoundry-community/cf-containers-broker/pull/67) and this clause in our operator file:

```yaml
# Remove Dashboard OAuth clients
- type: remove
  path: /instance_groups/name=docker/jobs/name=cf-containers-broker/properties/services/name=redis32/dashboard_client
```

**Comment by drnic** [comment]
I'm having trouble the docker-boshrelease's CI at the moment. Hopefully can get it fixed and get your PR pushed thru to a new boshrelease

________________________________

**Comment by aeijdenberg** [comment]
@drnic - did you have any luck with a new bosh release for this? (encountered this issue today installing to a new environment)

**Comment by drnic** [comment]
@jhunt whilst you've been away our bosh-lite49 used for CI has acquired a new behavior - internal containers don't seem to be able to communicate with the CF haproxy via the host machine IP. Could you have a look and see if you can have any bright idea insights about a fix?

**Comment by jhunt** [comment]
@drnic: will do

**Comment by jhunt** [comment]
I may need you to explain to me what is going on with lite49, since there seems to be a lot of leftover stuff (last I checked, CI was supposed to clean up after itself when it finished)

**Comment by drnic** [comment]
I'll close this now as fixed by @aeijdenberg PR earlier. Please reopen if I'm confused and the original issue persists.
