### ISSUE TITLE
Follow up with k8 service-catalog

### ISSUE THREAD

**Issue by cforce** [cloudfoundry-community/docker-broker-deployment#6]
Are there any more hints how that would work with when the container run in kubernetes?
https://github.com/kubernetes-incubator/service-catalog
As i understood kubo - it does not provide that out of the box.

**Comment by drnic** [comment]
I'm new to K8s and have only just started deploying it + kicking its tyres. Perhaps something will come from this.

**Comment by drnic** [comment]
I'm going to close this ticket. If I/someone works on a k8s extension for cf-containers-broker, then I'd suggest a new kubernetes-broker-deployment repo to contain the example manifests.
